/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casinoGame;

import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author mr200179
 */
public class higherorlower extends javax.swing.JFrame {
private int cardValue=0;
private int newValue=0;
private int inARow=0;
public ArrayList<Authentication> UserList = new ArrayList<>();
    /**
     * Creates new form playingBoard
     */
    public higherorlower() {
        initComponents();
          UserList = FileHandling.readFile();
        LogInSystem index = new LogInSystem();
        jLabel4.setText("Coins: "+UserList.get(index.getCurrentUName()).getCurrency());
        c10.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        c7.setVisible(false);
        c8.setVisible(false);
        c9.setVisible(false);
        ca.setVisible(false);
        cj.setVisible(false);
        ck.setVisible(false);
        cq.setVisible(false);
        higher.setVisible(false);
        lower.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        cj = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        c10 = new javax.swing.JLabel();
        ca = new javax.swing.JLabel();
        ck = new javax.swing.JLabel();
        cq = new javax.swing.JLabel();
        higher = new javax.swing.JButton();
        lower = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/red-start-png-5.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(820, 410, 320, 300);

        cj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/JH.png"))); // NOI18N
        getContentPane().add(cj);
        cj.setBounds(680, 390, 790, 1070);

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/2C.png"))); // NOI18N
        getContentPane().add(c2);
        c2.setBounds(680, 310, 1160, 1240);

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/3H.png"))); // NOI18N
        getContentPane().add(c3);
        c3.setBounds(680, 390, 1140, 1080);

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/4D.png"))); // NOI18N
        getContentPane().add(c4);
        c4.setBounds(680, 380, 1040, 1090);

        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/5S.png"))); // NOI18N
        getContentPane().add(c5);
        c5.setBounds(680, 390, 830, 1080);

        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/6C.png"))); // NOI18N
        getContentPane().add(c6);
        c6.setBounds(680, 390, 840, 1070);

        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/7D.png"))); // NOI18N
        getContentPane().add(c7);
        c7.setBounds(680, 380, 820, 1090);

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/8H.png"))); // NOI18N
        getContentPane().add(c8);
        c8.setBounds(680, 380, 1060, 1090);

        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/9S.png"))); // NOI18N
        getContentPane().add(c9);
        c9.setBounds(680, 370, 1140, 1110);

        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/10C.png"))); // NOI18N
        getContentPane().add(c10);
        c10.setBounds(680, 390, 750, 1080);

        ca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/AD.png"))); // NOI18N
        getContentPane().add(ca);
        ca.setBounds(680, 370, 830, 1120);

        ck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/KS.png"))); // NOI18N
        getContentPane().add(ck);
        ck.setBounds(680, 390, 1100, 1070);

        cq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/QC.png"))); // NOI18N
        getContentPane().add(cq);
        cq.setBounds(680, 400, 691, 1056);

        higher.setFont(new java.awt.Font("Niagara Solid", 0, 36)); // NOI18N
        higher.setText("higher");
        higher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherActionPerformed(evt);
            }
        });
        getContentPane().add(higher);
        higher.setBounds(360, 410, 160, 60);

        lower.setFont(new java.awt.Font("Niagara Solid", 0, 36)); // NOI18N
        lower.setText("lower");
        lower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerActionPerformed(evt);
            }
        });
        getContentPane().add(lower);
        lower.setBounds(360, 490, 160, 60);

        jLabel4.setFont(new java.awt.Font("Niagara Solid", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 60, 600, 120);

        jLabel3.setFont(new java.awt.Font("Niagara Solid", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("For every one you get right win 50 coins, get one wrong and lose 100");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 230, 840, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/backdrop.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -220, 2450, 1450);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void isUserBankrupt(){
    LogInSystem useraccount = new LogInSystem();
     if ((UserList.get(useraccount.getCurrentUName()).getCurrency()) <= 0) {
                UserList.remove((useraccount.getCurrentUName()));
                FileHandling.writeFile(UserList);
                insufficientFunds start = new insufficientFunds();
                Toolkit tk = Toolkit.getDefaultToolkit();
                int width = (int) tk.getScreenSize().getWidth();
                int height = (int) tk.getScreenSize().getHeight();

                start.setSize(width, height);
                start.setVisible(true);
                this.dispose();

            }else{
             NewJFrame start = new NewJFrame(); 
        Toolkit tk = Toolkit.getDefaultToolkit();
        int width =(int) tk.getScreenSize().getWidth();
         int height =(int) tk.getScreenSize().getHeight();

        start.setSize(width,height);
        start.setVisible(true);
        this.dispose();
     }
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Random rand= new Random();
       int cardNum=rand.nextInt((13 - 2) + 1) + 2;
       int cardType=rand.nextInt(4);
       if(cardNum==1){//                        ace
           
           ca.setVisible(true);
           cardValue=1;
       }else if (cardNum==2){
           c2.setVisible(true);
           cardValue=2;
       }else if (cardNum==3){
           c3.setVisible(true);
           cardValue=3;
       }else if (cardNum==4){
           c4.setVisible(true);
           cardValue=4;
       }else if (cardNum==5){
           c5.setVisible(true);
           cardValue=5;
       }else if (cardNum==6){
           c6.setVisible(true);
           cardValue=6;
       }else if (cardNum==7){
           c7.setVisible(true);
           cardValue=7;
       }else if (cardNum==8){
           c8.setVisible(true);
           cardValue=8;
       }else if (cardNum==9){
           c9.setVisible(true);
           cardValue=9;
       }else if (cardNum==10){
           c10.setVisible(true);
           cardValue=10;
       }else if (cardNum==11){//queen
           cq.setVisible(true);
           cardValue=10;
       }else if (cardNum==12){//king
           ck.setVisible(true);
           cardValue=10;
       }else if (cardNum==13){//jack
           cj.setVisible(true);
           cardValue=10;
       }
        jButton2.setVisible(false);
        higher.setVisible(true);
        lower.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void higherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherActionPerformed
         c10.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        c7.setVisible(false);
        c8.setVisible(false);
        c9.setVisible(false);
        ca.setVisible(false);
        cj.setVisible(false);
        ck.setVisible(false);
        cq.setVisible(false);
        higher.setVisible(false);
        lower.setVisible(false);
        
        newValue=cardValue;
        cardValue=0;
        
        Random rand= new Random();
       int cardNum=rand.nextInt((13 - 2) + 1) + 2;
       int cardType=rand.nextInt(4);
       if(cardNum==1){//                        ace
           
           ca.setVisible(true);
           cardValue=1;
       }else if (cardNum==2){
           c2.setVisible(true);
           cardValue=2;
       }else if (cardNum==3){
           c3.setVisible(true);
           cardValue=3;
       }else if (cardNum==4){
           c4.setVisible(true);
           cardValue=4;
       }else if (cardNum==5){
           c5.setVisible(true);
           cardValue=5;
       }else if (cardNum==6){
           c6.setVisible(true);
           cardValue=6;
       }else if (cardNum==7){
           c7.setVisible(true);
           cardValue=7;
       }else if (cardNum==8){
           c8.setVisible(true);
           cardValue=8;
       }else if (cardNum==9){
           c9.setVisible(true);
           cardValue=9;
       }else if (cardNum==10){
           c10.setVisible(true);
           cardValue=10;
       }else if (cardNum==11){//queen
           cq.setVisible(true);
           cardValue=10;
       }else if (cardNum==12){//king
           ck.setVisible(true);
           cardValue=10;
       }else if (cardNum==13){//jack
           cj.setVisible(true);
           cardValue=10;
       }
        jButton2.setVisible(false);
        higher.setVisible(true);
        lower.setVisible(true);
        LogInSystem useraccount = new LogInSystem();
        int newCoins;
        if (cardValue>newValue){
            
          newCoins =UserList.get(useraccount.getCurrentUName()).getCurrency()+50;
            jLabel4.setText(""+newCoins);
            UserList.get(useraccount.getCurrentUName()).setCurrency(newCoins);
            FileHandling.writeFile(UserList);
        }else{
            newCoins =UserList.get(useraccount.getCurrentUName()).getCurrency()-100;
            jLabel4.setText(""+newCoins);
            UserList.get(useraccount.getCurrentUName()).setCurrency(newCoins);
            FileHandling.writeFile(UserList);
           
            isUserBankrupt();
            
            
            
        
        
        }
    }//GEN-LAST:event_higherActionPerformed

    private void lowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerActionPerformed
         c10.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        c7.setVisible(false);
        c8.setVisible(false);
        c9.setVisible(false);
        ca.setVisible(false);
        cj.setVisible(false);
        ck.setVisible(false);
        cq.setVisible(false);
        higher.setVisible(false);
        lower.setVisible(false);
        
        newValue=cardValue;
        cardValue=0;
        
        Random rand= new Random();
       int cardNum=rand.nextInt((13 - 2) + 1) + 2;
       int cardType=rand.nextInt(4);
       if(cardNum==1){//                        ace
           
           ca.setVisible(true);
           cardValue=1;
       }else if (cardNum==2){
           c2.setVisible(true);
           cardValue=2;
       }else if (cardNum==3){
           c3.setVisible(true);
           cardValue=3;
       }else if (cardNum==4){
           c4.setVisible(true);
           cardValue=4;
       }else if (cardNum==5){
           c5.setVisible(true);
           cardValue=5;
       }else if (cardNum==6){
           c6.setVisible(true);
           cardValue=6;
       }else if (cardNum==7){
           c7.setVisible(true);
           cardValue=7;
       }else if (cardNum==8){
           c8.setVisible(true);
           cardValue=8;
       }else if (cardNum==9){
           c9.setVisible(true);
           cardValue=9;
       }else if (cardNum==10){
           c10.setVisible(true);
           cardValue=10;
       }else if (cardNum==11){//queen
           cq.setVisible(true);
           cardValue=10;
       }else if (cardNum==12){//king
           ck.setVisible(true);
           cardValue=10;
       }else if (cardNum==13){//jack
           cj.setVisible(true);
           cardValue=10;
       }
        jButton2.setVisible(false);
        higher.setVisible(true);
        lower.setVisible(true);
        LogInSystem useraccount = new LogInSystem();
        int newCoins;
        if (cardValue<newValue){
             newCoins =UserList.get(useraccount.getCurrentUName()).getCurrency()+50;
            jLabel4.setText(""+newCoins);
            UserList.get(useraccount.getCurrentUName()).setCurrency(newCoins);
            FileHandling.writeFile(UserList);
        }else{
            newCoins =UserList.get(useraccount.getCurrentUName()).getCurrency()-100;
            jLabel4.setText(""+newCoins);
            UserList.get(useraccount.getCurrentUName()).setCurrency(newCoins);
            FileHandling.writeFile(UserList);
            isUserBankrupt();
             
      
        
        }
    }//GEN-LAST:event_lowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(higherorlower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(higherorlower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(higherorlower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(higherorlower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new higherorlower().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JLabel ca;
    private javax.swing.JLabel cj;
    private javax.swing.JLabel ck;
    private javax.swing.JLabel cq;
    private javax.swing.JButton higher;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton lower;
    // End of variables declaration//GEN-END:variables
}
