/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casinoGame;

import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author maxra
 */
public class LogInSystem extends javax.swing.JFrame {

    private static int currentUNameIndex ;

  

    public int getCurrentUName() {
        return currentUNameIndex;
    }
    public ArrayList<Authentication> UserList = new ArrayList<>();

    /**
     * Creates new form LogInSystem
     */
    public LogInSystem() {
        initComponents();
        UserList = FileHandling.readFile();
        NewSubmit.setVisible(false);
        NewPass.setVisible(false);
        NewUser.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);

        ExistingSubmit.setVisible(false);
        ExistingPass.setVisible(false);
        ExistingUser.setVisible(false);
        jLabel6.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        errorMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExistingUser = new javax.swing.JTextField();
        ExistingPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExistingSubmit = new javax.swing.JButton();
        NewPass = new javax.swing.JTextField();
        NewUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NewSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        existingAcc = new javax.swing.JButton();
        newAcc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ExistingUser.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        getContentPane().add(ExistingUser);
        ExistingUser.setBounds(1090, 650, 190, 26);

        ExistingPass.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        ExistingPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistingPassActionPerformed(evt);
            }
        });
        getContentPane().add(ExistingPass);
        ExistingPass.setBounds(1090, 720, 190, 26);

        jLabel1.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1000, 650, 90, 20);

        jLabel2.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1000, 720, 90, 20);

        ExistingSubmit.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        ExistingSubmit.setText("submit");
        ExistingSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistingSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(ExistingSubmit);
        ExistingSubmit.setBounds(1100, 760, 110, 29);

        NewPass.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        getContentPane().add(NewPass);
        NewPass.setBounds(740, 720, 190, 26);

        NewUser.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        getContentPane().add(NewUser);
        NewUser.setBounds(740, 650, 190, 26);

        jLabel3.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 650, 90, 20);

        jLabel4.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 720, 80, 20);

        NewSubmit.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        NewSubmit.setText("submit");
        NewSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(NewSubmit);
        NewSubmit.setBounds(790, 760, 100, 29);

        jLabel5.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        jLabel5.setText("Sign Up");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 600, 60, 20);

        jLabel6.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        jLabel6.setText("Sign In");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1000, 600, 60, 20);

        existingAcc.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        existingAcc.setText("existing user");
        existingAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingAccActionPerformed(evt);
            }
        });
        getContentPane().add(existingAcc);
        existingAcc.setBounds(990, 250, 120, 35);

        newAcc.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        newAcc.setText("new account");
        newAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccActionPerformed(evt);
            }
        });
        getContentPane().add(newAcc);
        newAcc.setBounds(720, 250, 120, 35);

        jLabel8.setFont(new java.awt.Font("Niagara Solid", 1, 150)); // NOI18N
        jLabel8.setText("Welcome");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(730, 40, 438, 203);

        errorMessage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        errorMessage.setText("Invalid Password, try agin or create a new account");
        getContentPane().add(errorMessage);
        errorMessage.setBounds(1020, 820, 350, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/backdrop.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -380, 2660, 1770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExistingPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistingPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExistingPassActionPerformed

    private void ExistingSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistingSubmitActionPerformed

        for (int i = 0; i < UserList.size(); i++) {
            String pword = new String(ExistingPass.getPassword());
            String uname = ExistingUser.getText();
            
         
            if ((UserList.get(i).getUserame().equals(uname)) && (UserList.get(i).getPassWord().equals(pword))) {
   currentUNameIndex = i;
                MainMenu start = new MainMenu();
                Toolkit tk = Toolkit.getDefaultToolkit();
                int width = (int) tk.getScreenSize().getWidth();
                int height = (int) tk.getScreenSize().getHeight();

                start.setSize(width, height);
                start.setVisible(true);
                this.dispose();
            } else {
                errorMessage.setVisible(true);
            }
        }
    }//GEN-LAST:event_ExistingSubmitActionPerformed

    private void NewSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSubmitActionPerformed
        String UserName = NewUser.getText();
        String PassWord = NewPass.getText();
        int coins = 500;
        Authentication User = new Authentication(UserName, PassWord, 500);
        UserList.add(User);
        FileHandling.writeFile(UserList);
        currentUNameIndex = UserList.size()-1;
        MainMenu start = new MainMenu();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int width = (int) tk.getScreenSize().getWidth();
        int height = (int) tk.getScreenSize().getHeight();

        start.setSize(width, height);
        start.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_NewSubmitActionPerformed

    private void newAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccActionPerformed
        ExistingSubmit.setVisible(false);
        ExistingPass.setVisible(false);
        ExistingUser.setVisible(false);
        jLabel6.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        errorMessage.setVisible(false);
        NewSubmit.setVisible(true);
        NewPass.setVisible(true);
        NewUser.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
    }//GEN-LAST:event_newAccActionPerformed

    private void existingAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingAccActionPerformed
        ExistingSubmit.setVisible(true);
        ExistingPass.setVisible(true);
        ExistingUser.setVisible(true);
        jLabel6.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);

        NewSubmit.setVisible(false);
        NewPass.setVisible(false);
        NewUser.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
    }//GEN-LAST:event_existingAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ExistingPass;
    private javax.swing.JButton ExistingSubmit;
    private javax.swing.JTextField ExistingUser;
    private javax.swing.JTextField NewPass;
    private javax.swing.JButton NewSubmit;
    private javax.swing.JTextField NewUser;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JButton existingAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton newAcc;
    // End of variables declaration//GEN-END:variables
}
