/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casinoGame;

import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author maxra
 */
public class SlotMachine extends javax.swing.JFrame {
public ArrayList<Authentication> UserList = new ArrayList<>();
    /**
     * Creates new form SlotMachine
     */
    public SlotMachine() {
        initComponents();
        makeInvisible();
        UserList = FileHandling.readFile();
        LogInSystem index = new LogInSystem();
        jLabel3.setText("Coins: "+UserList.get(index.getCurrentUName()).getCurrency());
    }

    public void makeInvisible() {
        bar1.setVisible(false);
        bell1.setVisible(false);
        cherry1.setVisible(false);
        diamond1.setVisible(false);
        heart1.setVisible(false);
        horseShoe1.setVisible(false);
        lemon1.setVisible(false);
        melon1.setVisible(false);
        seven1.setVisible(false);

        bar2.setVisible(false);
        bell2.setVisible(false);
        cherry2.setVisible(false);
        diamond2.setVisible(false);
        heart2.setVisible(false);
        horseShoe2.setVisible(false);
        lemon2.setVisible(false);
        melon2.setVisible(false);
        seven2.setVisible(false);

        bar3.setVisible(false);
        bell3.setVisible(false);
        cherry3.setVisible(false);
        diamond3.setVisible(false);
        heart3.setVisible(false);
        horseShoe3.setVisible(false);
        lemon3.setVisible(false);
        melon3.setVisible(false);
        seven3.setVisible(false);

        winner.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cost = new javax.swing.JLabel();
        diamond1 = new javax.swing.JLabel();
        lemon1 = new javax.swing.JLabel();
        melon1 = new javax.swing.JLabel();
        heart1 = new javax.swing.JLabel();
        seven1 = new javax.swing.JLabel();
        bell1 = new javax.swing.JLabel();
        bar1 = new javax.swing.JLabel();
        cherry1 = new javax.swing.JLabel();
        horseShoe1 = new javax.swing.JLabel();
        diamond2 = new javax.swing.JLabel();
        lemon2 = new javax.swing.JLabel();
        melon2 = new javax.swing.JLabel();
        heart2 = new javax.swing.JLabel();
        seven2 = new javax.swing.JLabel();
        bell2 = new javax.swing.JLabel();
        bar2 = new javax.swing.JLabel();
        cherry2 = new javax.swing.JLabel();
        horseShoe2 = new javax.swing.JLabel();
        diamond3 = new javax.swing.JLabel();
        lemon3 = new javax.swing.JLabel();
        melon3 = new javax.swing.JLabel();
        heart3 = new javax.swing.JLabel();
        seven3 = new javax.swing.JLabel();
        bell3 = new javax.swing.JLabel();
        bar3 = new javax.swing.JLabel();
        cherry3 = new javax.swing.JLabel();
        horseShoe3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        winner = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cost.setFont(new java.awt.Font("Niagara Solid", 0, 24)); // NOI18N
        cost.setText("50 coins per spin");
        getContentPane().add(cost);
        cost.setBounds(1680, 690, 160, 50);

        diamond1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194253747_iOS.jpg"))); // NOI18N
        getContentPane().add(diamond1);
        diamond1.setBounds(330, 490, 257, 246);

        lemon1.setBackground(new java.awt.Color(255, 255, 255));
        lemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194300000_iOS.jpg"))); // NOI18N
        getContentPane().add(lemon1);
        lemon1.setBounds(350, 490, 238, 241);

        melon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194301000_iOS.jpg"))); // NOI18N
        getContentPane().add(melon1);
        melon1.setBounds(350, 500, 237, 231);

        heart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194303000_iOS.jpg"))); // NOI18N
        getContentPane().add(heart1);
        heart1.setBounds(340, 490, 242, 242);

        seven1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194308000_iOS.jpg"))); // NOI18N
        getContentPane().add(seven1);
        seven1.setBounds(340, 490, 248, 248);

        bell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194309000_iOS.jpg"))); // NOI18N
        getContentPane().add(bell1);
        bell1.setBounds(330, 490, 258, 258);

        bar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194316000_iOS.jpg"))); // NOI18N
        getContentPane().add(bar1);
        bar1.setBounds(340, 490, 270, 260);

        cherry1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194315000_iOS.jpg"))); // NOI18N
        getContentPane().add(cherry1);
        cherry1.setBounds(330, 490, 290, 260);

        horseShoe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194314000_iOS.jpg"))); // NOI18N
        getContentPane().add(horseShoe1);
        horseShoe1.setBounds(330, 480, 260, 270);

        diamond2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194253747_iOS.jpg"))); // NOI18N
        getContentPane().add(diamond2);
        diamond2.setBounds(640, 490, 257, 246);

        lemon2.setBackground(new java.awt.Color(255, 255, 255));
        lemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194300000_iOS.jpg"))); // NOI18N
        getContentPane().add(lemon2);
        lemon2.setBounds(660, 490, 238, 241);

        melon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194301000_iOS.jpg"))); // NOI18N
        getContentPane().add(melon2);
        melon2.setBounds(660, 500, 237, 231);

        heart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194303000_iOS.jpg"))); // NOI18N
        getContentPane().add(heart2);
        heart2.setBounds(650, 490, 242, 242);

        seven2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194308000_iOS.jpg"))); // NOI18N
        getContentPane().add(seven2);
        seven2.setBounds(650, 490, 248, 248);

        bell2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194309000_iOS.jpg"))); // NOI18N
        getContentPane().add(bell2);
        bell2.setBounds(640, 490, 258, 258);

        bar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194316000_iOS.jpg"))); // NOI18N
        getContentPane().add(bar2);
        bar2.setBounds(650, 490, 270, 260);

        cherry2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194315000_iOS.jpg"))); // NOI18N
        getContentPane().add(cherry2);
        cherry2.setBounds(640, 490, 290, 260);

        horseShoe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194314000_iOS.jpg"))); // NOI18N
        getContentPane().add(horseShoe2);
        horseShoe2.setBounds(640, 480, 260, 270);

        diamond3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194253747_iOS.jpg"))); // NOI18N
        getContentPane().add(diamond3);
        diamond3.setBounds(940, 490, 257, 246);

        lemon3.setBackground(new java.awt.Color(255, 255, 255));
        lemon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194300000_iOS.jpg"))); // NOI18N
        getContentPane().add(lemon3);
        lemon3.setBounds(960, 490, 238, 241);

        melon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194301000_iOS.jpg"))); // NOI18N
        getContentPane().add(melon3);
        melon3.setBounds(960, 500, 237, 231);

        heart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194303000_iOS.jpg"))); // NOI18N
        getContentPane().add(heart3);
        heart3.setBounds(950, 490, 242, 242);

        seven3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194308000_iOS.jpg"))); // NOI18N
        getContentPane().add(seven3);
        seven3.setBounds(950, 490, 248, 248);

        bell3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194309000_iOS.jpg"))); // NOI18N
        getContentPane().add(bell3);
        bell3.setBounds(940, 490, 258, 258);

        bar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194316000_iOS.jpg"))); // NOI18N
        getContentPane().add(bar3);
        bar3.setBounds(950, 490, 270, 260);

        cherry3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194315000_iOS.jpg"))); // NOI18N
        getContentPane().add(cherry3);
        cherry3.setBounds(940, 490, 290, 260);

        horseShoe3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/20210203_194314000_iOS.jpg"))); // NOI18N
        getContentPane().add(horseShoe3);
        horseShoe3.setBounds(940, 480, 260, 270);

        jButton1.setFont(new java.awt.Font("Niagara Solid", 1, 64)); // NOI18N
        jButton1.setText("Spin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1590, 530, 270, 160);

        winner.setFont(new java.awt.Font("Niagara Solid", 0, 48)); // NOI18N
        winner.setForeground(new java.awt.Color(255, 255, 255));
        winner.setText("You won:");
        getContentPane().add(winner);
        winner.setBounds(1580, 180, 300, 90);

        jLabel3.setFont(new java.awt.Font("Niagara Solid", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 50, 500, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/slots2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 110, 1490, 810);

        jButton2.setFont(new java.awt.Font("Niagara Solid", 0, 36)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1660, 440, 130, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casinoGame/backdrop.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -80, 2530, 1170);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void isUserBankrupt(){
    LogInSystem useraccount = new LogInSystem();
     if ((UserList.get(useraccount.getCurrentUName()).getCurrency()) <= 0) {
                UserList.remove((useraccount.getCurrentUName()));
                FileHandling.writeFile(UserList);
                insufficientFunds start = new insufficientFunds();
                Toolkit tk = Toolkit.getDefaultToolkit();
                int width = (int) tk.getScreenSize().getWidth();
                int height = (int) tk.getScreenSize().getHeight();

                start.setSize(width, height);
                start.setVisible(true);
                this.dispose();

            }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        makeInvisible();
        Random rand = new Random();
         int newCoins;
        LogInSystem index = new LogInSystem();
         newCoins =UserList.get(index.getCurrentUName()).getCurrency()-50;
            jLabel3.setText(""+newCoins);
            UserList.get(index.getCurrentUName()).setCurrency(newCoins);
            FileHandling.writeFile(UserList);
        int Spinner1 = rand.nextInt((9 - 1) + 1) + 1;
        int Spinner2 = rand.nextInt((9 - 1) + 1) + 1;
        int Spinner3 = rand.nextInt((9 - 1) + 1) + 1;
        int Spinner1Value = 0;
        int Spinner2Value = 0;
        int Spinner3Value = 0;
        if (Spinner1 == 1) {
            bar1.setVisible(true);
            Spinner1Value = 1;
        } else if (Spinner1 == 2) {
            bell1.setVisible(true);
            Spinner1Value = 2;
        } else if (Spinner1 == 3) {
            cherry1.setVisible(true);
            Spinner1Value = 3;
        } else if (Spinner1 == 4) {
            diamond1.setVisible(true);
            Spinner1Value = 4;
        } else if (Spinner1 == 5) {
            heart1.setVisible(true);
            Spinner1Value = 5;
        } else if (Spinner1 == 6) {
            horseShoe1.setVisible(true);
            Spinner1Value = 6;
        } else if (Spinner1 == 7) {
            lemon1.setVisible(true);
            Spinner1Value = 7;
        } else if (Spinner1 == 8) {
            melon1.setVisible(true);
            Spinner1Value = 8;
        } else if (Spinner1 == 9) {
            seven1.setVisible(true);
            Spinner1Value = 9;
        }
        if (Spinner2 == 1) {
            bar2.setVisible(true);
            Spinner2Value = 1;
        } else if (Spinner2 == 2) {
            bell2.setVisible(true);
            Spinner2Value = 2;
        } else if (Spinner2 == 3) {
            cherry2.setVisible(true);
            Spinner2Value = 3;
        } else if (Spinner2 == 4) {
            diamond2.setVisible(true);
            Spinner2Value = 4;
        } else if (Spinner2 == 5) {
            heart2.setVisible(true);
            Spinner2Value = 5;
        } else if (Spinner2 == 6) {
            horseShoe2.setVisible(true);
            Spinner2Value = 6;
        } else if (Spinner2 == 7) {
            lemon2.setVisible(true);
            Spinner2Value = 7;
        } else if (Spinner2 == 8) {
            melon2.setVisible(true);
            Spinner2Value = 8;
        } else if (Spinner2 == 9) {
            seven2.setVisible(true);
            Spinner2Value = 9;
        }

        if (Spinner3 == 1) {
            bar3.setVisible(true);
            Spinner3Value = 1;
        } else if (Spinner3 == 2) {
            bell3.setVisible(true);
            Spinner3Value = 2;
        } else if (Spinner3 == 3) {
            cherry3.setVisible(true);
            Spinner3Value = 3;
        } else if (Spinner3 == 4) {
            diamond3.setVisible(true);
            Spinner3Value = 4;
        } else if (Spinner3 == 5) {
            heart3.setVisible(true);
            Spinner3Value = 5;
        } else if (Spinner3 == 6) {
            horseShoe3.setVisible(true);
            Spinner3Value = 6;
        } else if (Spinner3 == 7) {
            lemon3.setVisible(true);
            Spinner3Value = 7;
        } else if (Spinner3 == 8) {
            melon3.setVisible(true);
            Spinner3Value = 8;
        } else if (Spinner3 == 9) {
            seven3.setVisible(true);
            Spinner3Value = 9;
        }
       
        if ((Spinner1Value == Spinner2Value) && (Spinner2Value == Spinner3Value) && (Spinner3Value == 1)) {
            int winnings = 5000;
            winner.setText("You Won: " + winnings);
            winner.setVisible(true);
             newCoins =UserList.get(index.getCurrentUName()).getCurrency()+5000;
            jLabel3.setText(""+newCoins);
            UserList.get(index.getCurrentUName()).setCurrency(newCoins);
            FileHandling.writeFile(UserList);
        } else if ((Spinner1Value == Spinner2Value) && (Spinner2Value == Spinner3Value)) {
            int winnings = 1000;
            winner.setText("You Won: " + winnings);
            winner.setVisible(true);
             newCoins =UserList.get(index.getCurrentUName()).getCurrency()+1000;
            jLabel3.setText(""+newCoins);
            UserList.get(index.getCurrentUName()).setCurrency(newCoins);
            FileHandling.writeFile(UserList);
        }
        isUserBankrupt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          MainMenu start = new MainMenu();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int width = (int) tk.getScreenSize().getWidth();
        int height = (int) tk.getScreenSize().getHeight();

        start.setSize(width, height);
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bar1;
    private javax.swing.JLabel bar2;
    private javax.swing.JLabel bar3;
    private javax.swing.JLabel bell1;
    private javax.swing.JLabel bell2;
    private javax.swing.JLabel bell3;
    private javax.swing.JLabel cherry1;
    private javax.swing.JLabel cherry2;
    private javax.swing.JLabel cherry3;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel diamond1;
    private javax.swing.JLabel diamond2;
    private javax.swing.JLabel diamond3;
    private javax.swing.JLabel heart1;
    private javax.swing.JLabel heart2;
    private javax.swing.JLabel heart3;
    private javax.swing.JLabel horseShoe1;
    private javax.swing.JLabel horseShoe2;
    private javax.swing.JLabel horseShoe3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lemon1;
    private javax.swing.JLabel lemon2;
    private javax.swing.JLabel lemon3;
    private javax.swing.JLabel melon1;
    private javax.swing.JLabel melon2;
    private javax.swing.JLabel melon3;
    private javax.swing.JLabel seven1;
    private javax.swing.JLabel seven2;
    private javax.swing.JLabel seven3;
    private javax.swing.JLabel winner;
    // End of variables declaration//GEN-END:variables

}
