/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package higherorlower;

import java.util.Random;

/**
 *
 * @author mr200179
 */
public class playingBoard extends javax.swing.JFrame {
public int cardValue=0;
    /**
     * Creates new form playingBoard
     */
    public playingBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        c2 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setBackground(new java.awt.Color(51, 102, 0));
        jButton2.setForeground(new java.awt.Color(51, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/red-start-png-5.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 350, 320, 300);

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/2C.png"))); // NOI18N
        getContentPane().add(c2);
        c2.setBounds(1220, -40, 1280, 1060);

        h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/2H.png"))); // NOI18N
        getContentPane().add(h2);
        h2.setBounds(1230, -60, 691, 1056);

        s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/2S.png"))); // NOI18N
        s2.setText("jLabel3");
        getContentPane().add(s2);
        s2.setBounds(1230, -50, 729, 1056);

        d2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/2D.png"))); // NOI18N
        d2.setText("jLabel3");
        getContentPane().add(d2);
        d2.setBounds(1220, -20, 960, 1020);

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/3C.png"))); // NOI18N
        c3.setText("jLabel2");
        getContentPane().add(c3);
        c3.setBounds(1240, -40, 960, 1050);

        d3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/3D.png"))); // NOI18N
        d3.setText("jLabel2");
        getContentPane().add(d3);
        d3.setBounds(1230, -50, 850, 1080);

        h3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/3H.png"))); // NOI18N
        h3.setText("jLabel2");
        getContentPane().add(h3);
        h3.setBounds(1220, -40, 980, 1060);

        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/3S.png"))); // NOI18N
        s3.setText("jLabel2");
        getContentPane().add(s3);
        s3.setBounds(1220, -50, 960, 1080);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higherorlower/4C.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1220, -40, 1060, 1070);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Random rand= new Random();
       int cardNum=rand.nextInt((13 - 2) + 1) + 2;
       int cardType=rand.nextInt(4);
       if(cardNum==1){
           
           
           cardValue=1;
       }else if (cardNum==2){
           cardValue=2;
       }else if (cardNum==3){
           cardValue=3;
       }else if (cardNum==4){
           cardValue=4;
       }else if (cardNum==5){
           cardValue=5;
       }else if (cardNum==6){
           cardValue=6;
       }else if (cardNum==7){
           cardValue=7;
       }else if (cardNum==8){
           cardValue=8;
       }else if (cardNum==9){
           cardValue=9;
       }else if (cardNum==10){//king
           cardValue=10;
       }else if (cardNum==11){//queen
           cardValue=10;
       }else if (cardNum==12){//ace
           cardValue=10;
       }else if (cardNum==13){//jack
           cardValue=10;
       }
        jButton2.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playingBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    // End of variables declaration//GEN-END:variables
}
